name: MacOS CI

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**/CMakeLists.txt'
      - '.github/workflows/macos*.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**/CMakeLists.txt'
      - '.github/workflows/macos*.yml'

permissions:
  contents: read

jobs:
  macos-intel:
    uses: ./.github/workflows/macos-build.yml
    secrets: inherit
    with:
      name: "macOS Intel (x64)"
      version: ${{ github.ref_name }}
      platform: "darwin"
      os: macos-13
      arch: x64
      asset_ext: tar.gz
      upload_assets: false
      upload_url: ""

  macos-arm:
    uses: ./.github/workflows/macos-build.yml
    secrets: inherit
    with:
      name: "macOS Apple Silicon (arm64)"
      version: ${{ github.ref_name }}
      platform: "darwin"
      os: macos-14
      arch: arm64
      asset_ext: tar.gz
      upload_assets: false
      upload_url: ""
