name: Windows Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build-windows:
    uses: ./.github/workflows/win-build.yml
    secrets: inherit
    with:
      version: ${{ github.ref_name }}
      arch: 'amd64'
      upload_assets: true
      upload_url: ${{ github.event.release.upload_url }}
