name: Windows CI

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**/CMakeLists.txt'
      - '.github/workflows/*.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**/CMakeLists.txt'
      - '.github/workflows/*.yml'

permissions:
  contents: read

jobs:
  windows:
    uses: ./.github/workflows/win-build.yml
    secrets: inherit
    with:
      version:    ${{ github.ref_name }}
      upload_assets: false
      upload_url: ""
